[workspace]
authors = ["rifusaki <martinagmejia@gmail.com>"]
channels = ["conda-forge"]
name = "thermodynamics"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.6,<4"
pyserial = ">=3.5,<4"
ipython = ">=9.7.0,<10"
python = ">=3.12.12,<3.13"
ipykernel = ">=7.1.0,<8"
pandas = ">=2.3.3,<3"
openpyxl = ">=3.1.5,<4"
